apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ssm-operator
  namespace: kube-system
  annotations:
    # Substitute your account ID and IAM service role name below.
    eks.amazonaws.com/role-arn: arn:aws:iam::<accountnumber>:role/<iam-role-name>